Skip to content
Product
Solutions
Open Source
Pricing
Search
Sign in
Sign up
Formandodev
/
Formandodev
Public
Code
Issues
1
Pull requests
Actions
Projects
Security
Insights
Cobrinha
 main
@Formandodev
Formandodev committed on Mar 8, 2022 
1 parent 4d43102
commit 89af109
Showing 1 changed file with 47 additions and 0 deletions.
 47  
.github/workflows/blank.yml
@@ -0,0 +1,47 @@
# Nome da Actions:  
name: Snake Game

# Controlador do tempo que sera feito a atualização dos arquivos.
on:
  schedule:
      # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

# Permite executar na na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checks repo under $GITHUB_WORKSHOP, so your job can access it
      - uses: actions/checkout@v2

    # Repositorio que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Leticia-Rossii #Seu usuario
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Para as atualizações.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # the output branch we mentioned above
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

0 comments on commit 89af109
Please sign in to comment.
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Cobrinha · Formandodev/Formandodev@89af109 · GitHub
